const projects = {
  helpdesk: {title:'HelpDesk IA',intro:'Sistema de gestión de tickets de soporte técnico con asistencia de inteligencia artificial. Proyecto presentado como trabajo final.',problem:'Los incidentes de IT necesitan una descripción, una categoría y una prioridad antes de pasar a resolución. Este proyecto incorpora asistencia de IA a ese recorrido.',solution:'Una interfaz React permite crear y consultar tickets. El backend Express valida entradas con Zod, persiste los datos con Prisma y solicita a Gemini un análisis con categoría, prioridad y pasos sugeridos.',decisions:['Integración de IA en el backend para mantener la clave fuera del cliente.','Modo demo con respuestas simuladas cuando no hay una clave configurada o falla el proveedor.','PostgreSQL en producción y SQLite para el entorno local, según la documentación del proyecto.'],evidence:'Demuestra integración de servicios externos, validación de entradas y un flujo completo de interfaz, API y persistencia. El modo demo permite presentar el flujo; sus respuestas no equivalen a una inferencia real.',links:[['Repositorio','https://github.com/Gecko2087/helpdesk-ia'],['Vista interactiva','lab.html?project=helpdesk']]},
  passforge:{title:'PassForge',intro:'Aplicación de generación y organización de contraseñas, desarrollada como trabajo final de Next.js y Prisma.',problem:'Gestionar varias cuentas requiere generar claves y organizar registros asociados a cada usuario.',solution:'Una aplicación Next.js con TypeScript, categorías, sesiones con Better Auth y persistencia en PostgreSQL mediante Prisma.',decisions:['App Router y endpoints de API dentro de Next.js.','Modelos de usuarios, sesiones, categorías y contraseñas relacionados con Prisma.','Componentes de interfaz con Tailwind y Radix UI.'],evidence:'Demuestra modelado relacional, sesiones de usuario y construcción de una aplicación con TypeScript. Es un proyecto de aprendizaje; esta presentación no certifica su seguridad ni recomienda guardar credenciales reales.',links:[['Repositorio','https://github.com/Gecko2087/passforge-nextjs-prisma'],['Vista interactiva','lab.html?project=passforge']]},
  gamerhub:{title:'GamerHub',intro:'Plataforma para conectar jugadores, con frontend y backend en repositorios separados.',problem:'Una comunidad de jugadores necesita perfiles, información de juegos y una forma de autenticar usuarios.',solution:'Un cliente React se conecta a una API Express con rutas de autenticación, usuarios, perfiles y juegos. El backend utiliza Mongoose y MongoDB.',decisions:['Separación de cliente y servidor para mantener responsabilidades claras.','Autenticación basada en JWT y uso de bcryptjs en el backend.','Organización de endpoints por recursos: usuarios, perfiles y juegos.'],evidence:'Demuestra integración entre una interfaz y una API independiente, organización de rutas y uso de una base de datos documental. La vista interactiva es una edición independiente de catálogo y favoritos en memoria, sin conexión al backend original.',links:[['Frontend','https://github.com/Gecko2087/gamerhub-frontend'],['Backend','https://github.com/Gecko2087/gamerhub-backend'],['Vista interactiva','lab.html?project=gamerhub']]},
  taskapi:{title:'Task API',intro:'Administrador de tareas por usuario con una API Laravel y un cliente Vue.',problem:'La gestión de tareas requiere separar las operaciones administrativas de las acciones permitidas a cada usuario.',solution:'Una API REST expone operaciones CRUD para usuarios y tareas. Las rutas de administración y las de empleados utilizan autenticación Sanctum y middleware de roles.',decisions:['Grupos de rutas con middleware auth:sanctum.','Separación de acceso administrativo y acceso de empleados.','Backend Laravel y frontend Vue organizados como aplicaciones separadas.'],evidence:'Demuestra diseño de endpoints, autenticación y permisos declarados por rol. La vista interactiva ofrece un tablero y vistas por rol con datos ficticios. Simula las respuestas de la API; la autenticación y autorización del backend no se ejecutan en esa edición.',links:[['Repositorio','https://github.com/Gecko2087/task-rest-api'],['Vista interactiva','lab.html?project=taskapi']]}
};
const dialog=document.querySelector('#case-dialog');
const content=document.querySelector('#case-content');
let lastTrigger;
document.querySelectorAll('[data-project]').forEach(button=>button.addEventListener('click',()=>{
 const p=projects[button.dataset.project];lastTrigger=button;
 content.replaceChildren();
 const add=(tag,text)=>{const el=document.createElement(tag);el.textContent=text;content.append(el);return el;};
 add('h2',p.title).id='case-title';add('p',p.intro);add('h3','El problema');add('p',p.problem);add('h3','La solución');add('p',p.solution);add('h3','Decisiones técnicas');const ul=add('ul','');p.decisions.forEach(text=>{const li=document.createElement('li');li.textContent=text;ul.append(li);});add('h3','Qué demuestra');add('p',p.evidence);
 const links=add('div','');links.className='dialog-links';p.links.forEach(([text,url])=>{const a=document.createElement('a');a.href=url;a.textContent=text+' ↗';a.className='button primary';a.target='_blank';a.rel='noopener noreferrer';links.append(a);});
 add('p','La arquitectura describe el proyecto original. La vista interactiva es una edición independiente para reclutadores: usa datos ficticios y explica dentro de la aplicación los servicios que simula.').className='source-note';
 dialog.showModal();document.body.style.overflow='hidden';
}));
document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
dialog.addEventListener('close',()=>{document.body.style.overflow='';lastTrigger?.focus();});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});let count=0;document.querySelectorAll('.project').forEach(card=>{card.hidden=button.dataset.filter!=='all'&&!card.dataset.tags.split(' ').includes(button.dataset.filter);if(!card.hidden)count++;});document.querySelector('#filter-status').textContent=`${count} proyectos visibles`; }));
document.querySelector('#year').textContent=new Date().getFullYear();

