(() => {
const en=document.documentElement.lang==='en', prefix=en?'lab-en.html':'lab.html';
const projects={
 helpdesk:{name:'HelpDesk IA',index:'01',type:en?'SUPPORT WITH JUDGMENT':'SOPORTE CON CRITERIO',description:en?'Explore the support journey: describe an incident, review its classification and resolve the ticket.':'Explora el recorrido de soporte: describe un incidente, revisa la clasificación y resuelve el ticket.',stack:'React · Express · Prisma · Gemini',repo:'helpdesk-ia',boundary:en?'Interface demo with fictional data. Public analysis uses local rules, without Gemini calls.':'Demo de interfaz con datos ficticios. El análisis público usa reglas locales, sin llamadas a Gemini.'},
 passforge:{name:'PassForge',index:'02',type:en?'GENERATE / ORGANIZE':'GENERAR / ORGANIZAR',description:en?'Generate a password with Web Crypto, adjust its options and organize fictional records in a temporary vault.':'Genera una clave con Web Crypto, ajusta sus opciones y organiza registros ficticios en una bóveda temporal.',stack:'Next.js · TypeScript · Prisma · Better Auth',repo:'passforge-nextjs-prisma',boundary:en?'Real local generator. Temporary demo vault, without authentication or persistence. Use fictional records.':'Generador local real. Bóveda de demostración temporal, sin autenticación ni persistencia. Usa registros ficticios.'},
 gamerhub:{name:'GamerHub',index:'03',type:en?'PLAY / DISCOVER':'JUGAR / DESCUBRIR',description:en?'Explore the fictional catalog, filter by genre, open game details and build your favorites list.':'Explora el catálogo ficticio, filtra por género, abre los detalles y arma tu lista de favoritos.',stack:'React · Express · MongoDB · JWT',repo:'gamerhub-frontend',boundary:en?'Fictional catalog with local favorites. No connection to the original API or MongoDB.':'Catálogo ficticio con favoritos locales. Sin conexión a la API original ni a MongoDB.'}
};
const tabs=[...document.querySelectorAll('[data-showcase]')], stage=document.querySelector('#showcase');
const image=document.querySelector('#showcase-image'); let active='helpdesk';
function select(key){if(!projects[key])return;active=key;const p=projects[key];tabs.forEach(tab=>{const selected=tab.dataset.showcase===key;tab.setAttribute('aria-selected',String(selected));tab.tabIndex=selected?0:-1;});document.querySelector('#showcase-panel').setAttribute('aria-labelledby','tab-'+key);document.querySelector('#showcase-index').textContent=p.index+' / 03';document.querySelector('#showcase-type').textContent=p.index+' / '+p.type;const title=document.querySelector('#showcase-title');title.replaceChildren(document.createTextNode(p.name));const arrow=document.createElement('span');arrow.textContent='↗';title.append(arrow);document.querySelector('#showcase-description').textContent=p.description;document.querySelector('#showcase-stack').textContent=p.stack;document.querySelector('#showcase-boundary').textContent=p.boundary;document.querySelector('#screen-label').textContent=p.name.toUpperCase()+' / DEMO';document.querySelector('#showcase-demo').href=prefix+'?project='+key;document.querySelector('#showcase-code').href='https://github.com/Gecko2087/'+p.repo;const link=document.querySelector('#showcase-image-link');link.href=prefix+'?project='+key;link.setAttribute('aria-label',(en?'Try ':'Probar ')+p.name);stage.classList.remove('is-changing');image.onload=()=>{stage.classList.add('is-changing');};image.src='project-'+key+(en?'-en':'')+'.png';image.alt=(en?'Authentic screenshot of the interactive demo of ':'Captura auténtica de la demo interactiva de ')+p.name+(en?' with fictional data':' con datos ficticios');}
tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>select(tab.dataset.showcase));tab.addEventListener('keydown',event=>{let next=index;if(event.key==='ArrowRight')next=(index+1)%tabs.length;else if(event.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;event.preventDefault();select(tabs[next].dataset.showcase);tabs[next].focus();});});
const toggle=document.querySelector('#motion-toggle');toggle.addEventListener('click',()=>{const paused=document.body.classList.toggle('motion-paused');toggle.setAttribute('aria-pressed',String(paused));toggle.setAttribute('aria-label',en?(paused?'Enable animations':'Pause animations'):(paused?'Activar animaciones':'Pausar animaciones'));toggle.textContent=paused?'▷':'Ⅱ';});
if(matchMedia('(prefers-reduced-motion: reduce)').matches){document.body.classList.add('motion-paused');toggle.setAttribute('aria-pressed','true');toggle.setAttribute('aria-label',en?'Reduced motion follows your system settings':'Movimiento reducido según tu sistema');toggle.disabled=true;toggle.textContent='▷';}
if(en)select(active);
})();
